#!/bin/sh
#

EVENTS="

EXTNAME	EVENTS

x	y
-	-
512	511
512	512
512	513
512	514
512	515
511	512
512	512
513	512
514	512
515	512
511	511
510	510
509	509
508	508
507	507"

center=257:768,257:768

echo "\
	x%I=1:1024 y%I=1:1024		Ii1024	$center
	x%J=1:1024 y%J=1:1024		Ji1024	$center
	x%I=1:8192 y%I=1:8192		Ii8192	$center
	x%J=1:8192 y%J=1:8192		Ji8192	$center
	x%D=1:8192 y%D=1:8192		Di8192	$center
	x%E=1:8192 y%E=1:8192		Ei8192	$center
	x%D=0.5:8192.5 y%D=0.5:8192.5	Dd8192	$center
	x%E=0.5:8192.5 y%E=0.5:8192.5	Ed8192  $center"	\
| while read x y ext center; do
    echo "$EVENTS" | tabletofits $x $y | funimage STDIN[1][$center,1] STDOUT > data/cross1.$ext.fits
    echo "BINNED $center,1"    | funhead data/cross1.$ext.fits - - | overwrite data/cross1.$ext.fits
    echo "$EVENTS" | tabletofits $x $y | funimage STDIN[1][$center,2] STDOUT > data/cross2.$ext.fits
    echo "BINNED $center,2"    | funhead data/cross2.$ext.fits - - | overwrite data/cross2.$ext.fits
    echo "$EVENTS" | tabletofits $x $y | funimage STDIN[1][$center,4] STDOUT > data/cross4.$ext.fits
    echo "BINNED $center,4"    | funhead data/cross4.$ext.fits - - | overwrite data/cross4.$ext.fits
done

echo "$EVENTS" | tabletofits $x $y > data/events.fits

exit

echo "\
	circle128	circle(128,128,128)
	circle64	circle(128,128,64)
	circle32	circle(128,128,32)
	circle16	circle(128,128,16)
	circle8		circle(128,128,8)
	square		box(128,128,64,64)
	square45	box(128,128,64,64,45)
	square225	box(128,128,64,64,22.5)
	rect		box(128,128,64,32)
	rect45		box(128,128,64,32,45)
	rect225		box(128,128,64,32,22.5)
	ellipse128-64	ellipse(128,128,128,64)
	ellipse64-128	ellipse(128,128,64,128)
	ellipse64-12+45	ellipse(128,128,64,128,45)
	ellipse32-64+45	ellipse(128,128,32,64,45)
	ellipse16-64+45	ellipse(128,128,16,64,45)
	ellipse64-12-45	ellipse(128,128,64,128,-45)
	ellipse32-64-45	ellipse(128,128,32,64,-45)
	ellipse16-64-45	ellipse(128,128,16,64,-45)
	annuli0	annulus(128,128,0,10,20,30,40,50)
	annuli1	annulus(128,128,10,20,30,40,50)"			\
| while read name region ; do
     < /dev/null fldtotable x y | tabletofits x%B=1:256 y%B=1:256 	\
    | funimage "stdin[1][$region]" - mask=all 				\
    | funimage - - bitpix=8						\
    > data/$name.fits

    echo "REGN001 $region" | funhead data/$name.fits - - | overwrite data/$name.fits

done



